//
// Generated file, do not edit! Created by nedtool 5.6 from App_msg.msg.
//

#ifndef __APP_MSG_M_H
#define __APP_MSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>App_msg.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message App_msg extends cPacket
 * {
 *     string data = "IF YOU WANT TO SHOOT SHOOT, DONT TALK!";
 * }
 * </pre>
 */
class App_msg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string data;

  private:
    void copy(const App_msg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const App_msg&);

  public:
    App_msg(const char *name=nullptr, short kind=0);
    App_msg(const App_msg& other);
    virtual ~App_msg();
    App_msg& operator=(const App_msg& other);
    virtual App_msg *dup() const override {return new App_msg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getData() const;
    virtual void setData(const char * data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const App_msg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, App_msg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APP_MSG_M_H

